name: Update Badges on Label Removal

on:
  pull_request_target:
    types:
      - unlabeled

jobs:
  update_badges:
    name: Update badges
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment
        id: env
        uses: actions/github-script@v6
        if: startsWith(github.event.label.name, 'lock:artemis-test')
        with:
          script: |
            const labelName = context.payload.label.name;
            const badge = labelName.replace(/^lock:artemis-test/, '');
            core.setOutput('BADGE', badge);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update badge
        uses: RubbaBoy/BYOB@v1.3.0
        if: startsWith(github.event.label.name, 'lock:artemis-test')
        with:
          NAME: "artemis-test${{ steps.env.outputs.BADGE }}"
          LABEL: "artemis-test${{ steps.env.outputs.BADGE }}.artemis.cit.tum.de"
          STATUS: ${{ github.event.pull_request.head.ref }}
          COLOR: green
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
