name: Pull Request Closed

on:
  pull_request_target:
    types: [closed]

jobs:
  process_labels:
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.process.outputs.labels }}
      badges: ${{ steps.process.outputs.badges }}
    steps:
      - name: Process Labels
        id: process
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const labelsToRemove = [];
            const labelsToProcess = [];

            // Get the PR number
            const prNumber = context.payload.pull_request.number;

            // Iterate through labels on the PR
            for (const label of context.payload.pull_request.labels) {
              const labelName = label.name;
              const regex = /^lock:artemis-test(\d+)$/;

              if (regex.test(labelName)) {
                // Extract the part after "lock:" using capture groups
                const extractedLabel = labelName.match(regex)[1];
                labelsToProcess.push(extractedLabel);
                labelsToRemove.push(labelName);
              }
            }

            // Do something with the extracted labels
            console.log('Labels to process:', labelsToProcess);

            // Use the labelsToRemove array to remove the matching labels
            core.setOutput('badges', JSON.stringify(labelsToProcess));
            core.setOutput('labels', labelsToRemove.join(', '));


  remove_labels:
    needs: process_labels
    runs-on: ubuntu-latest

    steps:
      - name: Remove Labels
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: ${{ fromJSON(needs.process_labels.outputs.labels) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_badges:
    needs: process_labels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        badge: ${{ fromJson(needs.process_labels.outputs.badges) }}

    steps:
      - name: Echo
        run: |
          echo ${{ needs.process_labels.outputs.badges }}
          echo ${{ fromJson(needs.process_labels.outputs.badges) }}
          echo ${{ matrix.badge }} 
          echo ${{ github.event.pull_request.base.ref }}
      - name: Update badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: "artemis-test${{ matrix.badge }}"
          LABEL: "artemis-test${{ matrix.badge }}.artemis.cit.tum.de"
          STATUS: ${{ github.event.pull_request.base.ref }}
          COLOR: green
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

